version: 2

project_name: docker-sweep

before:
  hooks:
    - go mod tidy

builds:
  - id: docker-sweep
    main: ./main.go
    binary: docker-sweep
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - install.sh

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore\\(deps\\):"
  groups:
    - title: Features
      regexp: "^feat"
      order: 0
    - title: Bug Fixes
      regexp: "^fix"
      order: 1
    - title: Others
      order: 999

release:
  github:
    owner: midnattsol
    name: docker-sweep
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"
